"""Add last_otp_request to User model

Revision ID: 0161e1b96096
Revises: 582853fb0b48
Create Date: 2025-04-04 21:21:14.191362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0161e1b96096'
down_revision = '582853fb0b48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_otp_request', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_otp_request')

    # ### end Alembic commands ###
