"""Add failed_login_attempts and suspension_timestamp to User model

Revision ID: 8a76e47135cf
Revises: 0161e1b96096
Create Date: 2025-04-05 01:36:33.361580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a76e47135cf'
down_revision = '0161e1b96096'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('failed_login_attempts', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('suspension_timestamp', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('suspension_timestamp')
        batch_op.drop_column('failed_login_attempts')

    # ### end Alembic commands ###
